driver_translate = {'LEC': 'charles leclerc',
 'SAI': 'carlos sainz',
 'VER': 'max verstappen',
 'PER': 'sergio perez',
 'DEV': 'Nyck De Vries',
 'NOR': 'lando norris',
 'ALO': 'fernando alonso',
 'OCO': 'esteban ocon',
 'BOT': 'valtteri bottas',
 'ZHO': 'zhou guanyu',
 'GAS': 'pierre gasly',
 'TSU': 'yuki tsunoda',
 'MAG': 'kevin magnussen',
 'PIA': 'oscar piastri',
 'VET': 'sebastian vettel',
 'HUL': 'nico hulkenberg',
 'STR': 'lance stroll',
 'HAM': 'lewis hamilton',
 'RUS': 'george russell',
 'ALB': 'alexander albon',
 'SAR': 'logan sargeant'}