CREATE TABLE IF NOT EXISTS lapgaps (
    DriverID SERIAL PRIMARY KEY,
    Driver VARCHAR(50) NOT NULL,
    LapTime DECIMAL(8, 3) NOT NULL,
    SpeedMode VARCHAR(20) NOT NULL,
    FullName VARCHAR(100) NOT NULL,
    TeamName VARCHAR(100) NOT NULL,
    TeamColor VARCHAR(10) NOT NULL,
    DriverNumber INT NOT NULL,
    Event VARCHAR(50) NOT NULL,
    GP VARCHAR(50) NOT NULL,
    Year INT NOT NULL
);
